# -*- coding: utf-8 -*-
"""
Contingut en castellà de les pàgines (/es/). clau = slug català.
les claus que no hi són (horaris de disciplina, related, og...) s'hereten del CA
i es tradueixen al vol a genera_es(). els "cos"/"ld" d'horaris i preus s'injecten
des de genera_pagines.py.
"""

TRADUCCIONS_ES = {
    "ballet-classic": {
        "nom": "ballet clásico",
        "title": "clases de ballet clásico en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de ballet clásico en Sant Gervasi (Barcelona) para todas las edades: iniciación, infantil, juvenil y adultos. puntas y preparación RAD. 1ª clase gratuita.",
        "h1": "ballet clásico",
        "intro": "técnica, elegancia y una base para toda la vida. el ballet clásico es la columna vertebral de la escuela: desde la iniciación hasta las puntas y la preparación de exámenes.",
        "per_a_qui": "tenemos grupos de clásico para todas las edades y niveles: infantiles, juveniles y adultos (desde iniciación hasta avanzado). los más pequeños empiezan con la iniciación a la danza, y el recorrido llega hasta las clases de puntas y la preparación de exámenes oficiales RAD. no hace falta experiencia previa para empezar: te ayudamos a encontrar el grupo donde te sentirás a gusto.",
        "beneficis": [
            ("postura y conciencia corporal", "el clásico trabaja la alineación, el equilibrio y el control del cuerpo como ninguna otra disciplina."),
            ("disciplina y concentración", "la técnica pide atención y constancia — y eso se nota dentro y fuera de la sala."),
            ("la base de todas las danzas", "quien hace clásico tiene más facilidad para el contemporáneo, el jazz y cualquier otro estilo."),
            ("musicalidad", "aprender a escuchar la música y moverse con ella es un regalo para siempre."),
        ],
        "faqs": [
            ("¿hace falta experiencia para empezar ballet clásico?",
             "no. hay grupos de iniciación tanto para niños como para adultos, y la primera clase de prueba es gratuita para que lo compruebes sin compromiso."),
            ("¿hacéis puntas y exámenes oficiales?",
             "sí: hay clase de puntas para juveniles y preparamos alumnas y alumnos para los exámenes oficiales RAD (Royal Academy of Dance)."),
            ("¿un adulto puede empezar ballet desde cero?",
             "¡claro que sí! el grupo de adultos iniciación está pensado exactamente para eso. nunca es tarde para empezar."),
            ("¿qué hay que llevar a clase?",
             "para la clase de prueba, con ropa cómoda y ajustada es suficiente. cuando te apuntes, te orientaremos sobre medias, maillot y zapatillas."),
        ],
    },
    "dansa-contemporania": {
        "nom": "contemporáneo",
        "title": "clases de danza contemporánea en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de danza contemporánea en Sant Gervasi (Barcelona): movimiento libre y orgánico, técnica y creación. grupos infantiles, juveniles y adultos. 1ª clase gratuita.",
        "h1": "danza contemporánea",
        "intro": "movimiento libre y orgánico: la técnica al servicio de la expresión. en el contemporáneo hay espacio para crear, improvisar y encontrar tu propia manera de moverte.",
        "per_a_qui": "ofrecemos contemporáneo desde infantil hasta adultos, con grupos juveniles por niveles y grupos de adultos intermedio y avanzado. es una disciplina perfecta tanto para quien viene del clásico y quiere liberar el movimiento como para quien empieza y busca una danza expresiva y actual.",
        "beneficis": [
            ("expresión y creatividad", "el contemporáneo te invita a crear y a decir cosas con el cuerpo, no solo a ejecutar pasos."),
            ("un cuerpo fuerte y flexible", "trabajo de suelo, caídas, espirales: fuerza y movilidad reales para todo el cuerpo."),
            ("conexión con uno mismo", "respiración, peso, fluidez — un rato para escucharte y liberar tensiones."),
        ],
        "faqs": [
            ("¿qué se trabaja en una clase de contemporáneo?",
             "técnica (trabajo de suelo, espirales, saltos), improvisación y creación coreográfica, siempre adaptado al nivel del grupo."),
            ("¿hay que haber hecho ballet antes?",
             "no es imprescindible. una base de clásico ayuda, pero hay grupos donde puedes empezar desde cero — la clase de prueba gratuita es la mejor manera de comprobarlo."),
            ("¿contemporáneo o clásico: cuál elijo?",
             "si buscas estructura y técnica pura, clásico; si buscas expresión y movimiento libre, contemporáneo. muchas alumnas hacen los dos: se complementan muy bien."),
        ],
    },
    "jazz": {
        "nom": "jazz",
        "title": "clases de danza jazz en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de danza jazz en Sant Gervasi (Barcelona): energía, ritmo y coreografía para niños, jóvenes y adultos. primera clase de prueba gratuita.",
        "h1": "danza jazz",
        "intro": "energía, ritmo y coreografías que enganchan. el jazz es la puerta de entrada perfecta a la danza: dinámico, musical y divertidísimo.",
        "per_a_qui": "es una de las disciplinas con más grupos de la escuela: infantiles por edades, juveniles y adultos (desde básico hasta intermedio). si te gusta bailar con música actual y aprender coreografías con estilo, el jazz es tu sitio.",
        "beneficis": [
            ("coordinación y ritmo", "coreografías que trabajan memoria, musicalidad y coordinación de todo el cuerpo."),
            ("energía y forma física", "una clase de jazz es cardio disfrazado de diversión."),
            ("confianza sobre la pista", "aprendes a bailar delante de los demás y a disfrutarlo — ¡en el festival de fin de curso se nota!"),
        ],
        "faqs": [
            ("¿a partir de qué edad se puede hacer jazz?",
             "tenemos grupos infantiles desde bien pequeños, organizados por edades. en la clase de prueba gratuita veremos qué grupo le encaja mejor."),
            ("soy adulto y no he bailado nunca: ¿puedo?",
             "¡sí! el grupo de adultos básico está pensado para empezar desde cero, con buen rollo y sin presión."),
            ("¿qué diferencia hay entre jazz y hip-hop?",
             "el jazz bebe de la danza académica (línea, técnica, musicalidad) con música actual; el hip-hop viene de la cultura urbana, con un lenguaje más de calle. ¡prueba los dos y elige!"),
        ],
    },
    "hip-hop": {
        "nom": "hip-hop",
        "title": "clases de hip-hop en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de hip-hop y danzas urbanas en Sant Gervasi (Barcelona) para niños, jóvenes y adultos, de iniciación a avanzado. primera clase de prueba gratuita.",
        "h1": "hip-hop",
        "intro": "estilos urbanos, coreos actuales y mucha actitud. el hip-hop es la disciplina preferida de quienes quieren bailar lo que suena ahora mismo.",
        "per_a_qui": "desde infantil hasta adultos avanzado, con grupos juveniles por niveles. si tu hijo o hija baila todo el día delante del espejo, o si tú quieres aprender las coreos que ves en redes, aquí es donde empezar.",
        "beneficis": [
            ("actitud y confianza", "el hip-hop trabaja la presencia: bailar con seguridad se contagia al resto de la vida."),
            ("forma física de verdad", "potencia, resistencia y control — una clase urbana quema energía de lo lindo."),
            ("cultura y comunidad", "más que pasos: musicalidad, estilo propio y sentido de grupo."),
        ],
        "faqs": [
            ("mi hijo no ha bailado nunca: ¿puede empezar con hip-hop?",
             "es una de las mejores puertas de entrada: música que conocen, movimientos naturales y grupos por edades. la primera clase de prueba es gratuita."),
            ("¿hacéis hip-hop para adultos?",
             "sí, hay grupo de adultos avanzado los miércoles por la noche. si tu nivel es inicial, cuéntanoslo y te recomendamos el mejor encaje."),
            ("¿qué estilos urbanos trabajáis?",
             "la base es el hip-hop con apertura a otros estilos urbanos según el grupo y la coreografía. y si te tira el k-pop o los heels, ¡también tenemos clases!"),
        ],
    },
    "claque": {
        "nom": "claqué",
        "title": "clases de claqué en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de claqué en Sant Gervasi (Barcelona): el ritmo en los pies, de juvenil a adultos. primera clase de prueba gratuita.",
        "h1": "claqué",
        "intro": "el ritmo en los pies. el claqué convierte al bailarín en músico: cada paso es percusión, y cada coreografía, una canción.",
        "per_a_qui": "grupos juveniles y de adultos (intermedio). es una disciplina única: trabaja el ritmo como ninguna otra y engancha desde el primer día. si te gusta la música tanto como bailar, el claqué te hará feliz.",
        "beneficis": [
            ("oído y ritmo musical", "hacer música con los pies desarrolla una musicalidad finísima."),
            ("coordinación y agilidad", "pies rápidos, mente despierta: el claqué es gimnasia para el cerebro."),
            ("una tradición con mucho swing", "del musical americano a los escenarios de hoy — bailar claqué es pura elegancia."),
        ],
        "faqs": [
            ("¿necesito zapatos de claqué para probar?",
             "para la clase de prueba gratuita no hace falta: ven con calzado de suela dura y ya verás si te engancha (te enganchará)."),
            ("nunca he hecho claqué: ¿qué grupo me toca?",
             "habla con nosotros: según tu base de danza y ritmo te recomendaremos el grupo adecuado, y el primer día es de prueba."),
            ("¿los niños pueden hacer claqué?",
             "el claqué lo empezamos a partir de la etapa juvenil. para los más pequeños recomendamos empezar por jazz, clásico o hip-hop y dar el paso después."),
        ],
    },
    "ball-espanyol": {
        "nom": "baile español",
        "title": "clases de baile español en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de danza española en Sant Gervasi (Barcelona): tradición, carácter y técnica. grupos juveniles y adultos. primera clase de prueba gratuita.",
        "h1": "baile español",
        "intro": "tradición, carácter y una técnica con siglos de historia. la danza española es fuerza, elegancia y temperamento sobre el escenario.",
        "per_a_qui": "grupos juveniles y de adultos de nivel intermedio. si te atrae nuestra tradición de danza — el braceo, el carácter, la música española — esta es tu clase.",
        "beneficis": [
            ("carácter y presencia", "la danza española se baila con todo el cuerpo y con toda el alma."),
            ("técnica exigente y completa", "brazos, espalda, zapateado — un trabajo técnico que complementa cualquier otra danza."),
            ("patrimonio vivo", "bailar español es mantener viva una tradición única en el mundo."),
        ],
        "faqs": [
            ("¿puedo empezar sin nivel?",
             "los grupos actuales son de nivel intermedio, pero habla con nosotros: valoramos tu base en la clase de prueba gratuita y te decimos sinceramente si puedes incorporarte."),
            ("¿qué hay que llevar?",
             "para probar, ropa cómoda y un zapato con algo de tacón si lo tienes. después te orientaremos sobre el zapato de danza española."),
        ],
    },
    "dansa-oriental": {
        "nom": "danza oriental",
        "title": "clases de danza oriental en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de danza oriental (danza del vientre) en Sant Gervasi (Barcelona): expresión, técnica y feminidad. grupos juveniles y adultos. 1ª clase gratuita.",
        "h1": "danza oriental",
        "intro": "expresión, sensualidad y una técnica milenaria. la danza del vientre trabaja el cuerpo desde el centro y libera como pocas disciplinas.",
        "per_a_qui": "grupos juveniles y de adultos de nivel avanzado, por las noches. si buscas una danza expresiva, elegante y con una gran comunidad detrás, la danza oriental te atrapará.",
        "beneficis": [
            ("control del centro del cuerpo", "aislamientos, ondulaciones y vibraciones: un trabajo de técnica corporal finísimo."),
            ("expresión y autoestima", "una danza que celebra el cuerpo tal como es y te reconcilia con el espejo."),
            ("espalda y postura", "el trabajo de ondulaciones fortalece y flexibiliza toda la cadena posterior."),
        ],
        "faqs": [
            ("nunca la he practicado: ¿puedo apuntarme?",
             "los grupos actuales son avanzados, pero ven a la clase de prueba gratuita y valoramos tu encaje — o te avisamos cuando abramos grupo de iniciación."),
            ("¿qué me pongo para la clase?",
             "ropa cómoda que deje ver el movimiento de la cadera (leggings y top o camiseta ajustada). ¡el pañuelo de caderas te lo dejamos el primer día!"),
        ],
    },
    "k-pop-heels": {
        "nom": "k-pop & heels",
        "title": "clases de k-pop y heels en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de k-pop y heels en Sant Gervasi (Barcelona): las coreografías del momento y actitud sobre tacones. primera clase de prueba gratuita.",
        "h1": "k-pop & heels",
        "intro": "las coreos del momento y toda la actitud. del fenómeno k-pop al empoderamiento del heels: dos clases para bailar como en los videoclips.",
        "per_a_qui": "el k-pop es para juveniles que sueñan con las coreografías de sus grupos favoritos; el heels, para adultos avanzados que quieren trabajar actitud, línea y seguridad sobre tacones.",
        "beneficis": [
            ("bailar lo que te gusta", "coreografías reales de los artistas del momento: la motivación viene de serie."),
            ("actitud y seguridad", "el heels es una clase de empoderamiento puro: postura, presencia y confianza."),
            ("memoria coreográfica", "aprender coreos completas entrena la memoria y la limpieza de movimiento."),
        ],
        "faqs": [
            ("¿hay que saber bailar para hacer k-pop?",
             "no: las coreos se aprenden paso a paso y el grupo es juvenil. si le gusta el k-pop, la motivación hará el resto. ¡primera clase gratuita!"),
            ("¿qué tacones necesito para el heels?",
             "para probar, unos tacones cómodos y estables que ya tengas. después te aconsejaremos el calzado ideal para bailar con seguridad."),
        ],
    },
    "musical-interpretacio": {
        "nom": "musical & interpretación",
        "title": "clases de teatro musical para niños en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de musical e interpretación para niños en Sant Gervasi (Barcelona): bailar, cantar y actuar. primera clase de prueba gratuita.",
        "h1": "musical & interpretación",
        "intro": "bailar, cantar y actuar: el triple sueño del teatro musical, al alcance de los más pequeños. danza-teatro para crecer sobre el escenario.",
        "per_a_qui": "grupos infantiles los viernes por la tarde. perfecto para niños y niñas con vena artística que quieren hacerlo todo: moverse, cantar, interpretar personajes y perder la vergüenza encima de un escenario.",
        "beneficis": [
            ("expresión completa", "cuerpo, voz y emoción trabajando juntos — la expresividad se multiplica."),
            ("perder el miedo escénico", "actuar desde pequeños da una seguridad que dura toda la vida."),
            ("trabajo en equipo", "un musical se construye entre todos: escuchar, esperar el turno, brillar juntos."),
        ],
        "faqs": [
            ("mi hijo es tímido: ¿le irá bien?",
             "es justamente donde más florecen los tímidos: el juego teatral quita la vergüenza sin presión. prueba la primera clase gratuita y lo verás."),
            ("¿hay que saber cantar o bailar antes?",
             "para nada. se trabaja todo desde la base, jugando y por edades."),
        ],
    },
    "formacio-escenica": {
        "nom": "formación escénica",
        "title": "formación escénica para jóvenes en Barcelona · escola de dansa cristina colomé",
        "desc": "formación escénica los viernes por la tarde en Sant Gervasi (Barcelona): jazz, hip-hop, claqué, canto e interpretación en un solo pack. 1ª clase gratuita.",
        "h1": "formación escénica",
        "intro": "el entrenamiento completo del artista: jazz, hip-hop, claqué, canto e interpretación, todo en una misma tarde. para quien quiere el escenario de verdad.",
        "per_a_qui": "los viernes por la tarde, en formato pack, para jóvenes que quieren una formación artística completa: bailar varios estilos, cantar e interpretar. la mejor preparación para musicales, castings y escenarios — o simplemente para disfrutarlo todo.",
        "beneficis": [
            ("formación 360°", "cinco disciplinas en una tarde: la polivalencia que pide el escenario actual."),
            ("un precio de pack", "todo el viernes por la tarde por 85 €/mes — la manera más completa de formarse."),
            ("espíritu de compañía", "el grupo de los viernes funciona como una pequeña compañía: piña, proyecto y escenario."),
        ],
        "faqs": [
            ("¿cuánto cuesta la formación escénica?",
             "el pack completo de los viernes vale 85 € al mes (247 € si pagas el trimestre). la primera tarde de prueba es gratuita."),
            ("¿hace falta experiencia previa?",
             "no: hacen falta ganas. el formato multidisciplinar permite que cada uno crezca desde su punto de partida."),
        ],
    },
    "cos-benestar": {
        "nom": "cuerpo & bienestar",
        "title": "yoga, barre y zumba en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de yoga, barre y zumba en Sant Gervasi (Barcelona): cuídate bailando, por las mañanas y por las noches. primera clase de prueba gratuita.",
        "h1": "cuerpo & bienestar",
        "intro": "cuidarse también es bailar. yoga para respirar, barre para tonificar con ADN de danza y zumba para sudar sonriendo.",
        "per_a_qui": "para adultos de todas las edades y condiciones físicas: el barre por las mañanas (lunes y miércoles a las 11 h), y el yoga y la zumba por las noches. ninguna de estas clases pide experiencia — solo ganas de encontrarte bien.",
        "beneficis": [
            ("barre: tonificación con elegancia", "lo mejor del ballet (postura, piernas, core) sin necesidad de saber bailar."),
            ("yoga: respirar y desconectar", "flexibilidad, calma y una pausa de verdad en la semana."),
            ("zumba: cardio con sonrisa", "la clase donde sudar es una fiesta — ritmos latinos y energía arriba."),
        ],
        "faqs": [
            ("no he hecho nunca danza: ¿puedo hacer barre?",
             "el barre es para todo el mundo: se inspira en el ballet pero es una clase de tonificación, no de coreografía. ideal para empezar."),
            ("¿las clases de mañana son para quién?",
             "para quien tiene las mañanas libres y quiere empezar el día cuidándose: el barre de lunes y miércoles a las 11 h."),
        ],
    },
    "fit-dance": {
        "nom": "fit dance & femme empower",
        "title": "fit dance y femme empower en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de fit dance y femme empower en Sant Gervasi (Barcelona): sudor, fuerza y empoderamiento en grupo. primera clase de prueba gratuita.",
        "h1": "fit dance & femme empower",
        "intro": "sudor, fuerza y empoderamiento en grupo. dos clases para ponerse en forma bailando y salir de la sala con la autoestima por las nubes.",
        "per_a_qui": "para adultos que quieren entrenar bailando: el fit dance combina coreografía y acondicionamiento físico; el femme empower (nivel intermedio) trabaja actitud, fuerza y seguridad en un ambiente de sororidad total.",
        "beneficis": [
            ("ponerse en forma sin aburrirse", "cuando el entrenamiento es bailar, la constancia viene sola."),
            ("fuerza y actitud", "trabajo físico real con música alta y energía de grupo."),
            ("comunidad", "las clases de empoderamiento crean piña — vendrás por el ejercicio y te quedarás por la gente."),
        ],
        "faqs": [
            ("¿qué forma física necesito?",
             "ninguna en concreto para el fit dance: cada uno va a su ritmo y la intensidad se adapta. el femme empower pide un poco de rodaje."),
            ("¿qué llevo a clase?",
             "ropa deportiva, calzado cómodo, agua y toalla. el resto lo pone la música."),
        ],
    },
    "dansa-infantil": {
        "nom": "danza para niños y niñas",
        "nom_wa": "danza para niños",
        "title": "clases de danza para niños en Barcelona · escola de dansa cristina colomé",
        "desc": "extraescolar de danza para niños y niñas en Sant Gervasi (Barcelona): iniciación, clásico, jazz, hip-hop y más, por edades y niveles. 1ª clase gratuita.",
        "h1": "danza para niños y niñas",
        "intro": "la extraescolar que no parece una extraescolar: más de 25 años ayudando a niños y niñas a crecer bailando, a dos minutos del FGC Av. Tibidabo.",
        "per_a_qui": "desde la iniciación a la danza para los más pequeños hasta los grupos juveniles, todos los grupos se organizan por edades y niveles y tienen continuidad curso tras curso. las clases son por la tarde, pensadas para encajar con el horario escolar de las familias de Sant Gervasi, la Bonanova y el Putxet.",
        "beneficis": [
            ("psicomotricidad y postura", "la danza desarrolla coordinación, equilibrio y conciencia corporal en la edad de oro para hacerlo."),
            ("confianza y expresión", "bailar delante de los demás, actuar en el festival de fin de curso — la seguridad que se gana en la sala sale con ellos a la vida."),
            ("constancia y esfuerzo", "aprender una coreografía enseña el valor de la práctica mejor que mil sermones."),
            ("amistades que duran", "los grupos hacen piña: muchos de nuestros alumnos crecen juntos desde bien pequeños."),
        ],
        "disciplines": [
            ("iniciación a la danza", None, "el primer contacto con el movimiento y la música, para los más pequeños"),
            ("ballet clásico", "ballet-classic", "la base de todo, desde infantil hasta puntas y exámenes RAD"),
            ("jazz", "jazz", "energía y coreografía — la puerta de entrada más divertida"),
            ("hip-hop", "hip-hop", "estilos urbanos para los que bailan todo el día en casa"),
            ("contemporáneo", "dansa-contemporania", "expresión y movimiento libre para niños y juveniles"),
            ("musical & interpretación", "musical-interpretacio", "bailar, cantar y actuar los viernes"),
            ("k-pop", "k-pop-heels", "las coreos de sus ídolos, para juveniles"),
            ("formación escénica", "formacio-escenica", "el pack completo de artista de los viernes por la tarde"),
        ],
        "faqs": [
            ("¿a qué edad puede empezar mi hijo o hija?",
             "desde bien pequeños, con los grupos de iniciación a la danza. en la clase de prueba gratuita vemos qué grupo le encaja mejor por edad y madurez."),
            ("¿cuánto cuesta la extraescolar de danza?",
             "las cuotas infantiles van de los 56 €/mes (1 día por semana) a los 92 €/mes (4 días), con opción trimestral. la primera clase de prueba es gratuita."),
            ("¿cómo sabré si le gusta antes de apuntarlo?",
             "para eso la primera clase es gratuita y sin compromiso: lo traéis, lo prueba, y decidís con calma."),
            ("¿hacen actuaciones?",
             "¡sí! cada curso termina con el festival de fin de curso, el gran momento del año para alumnos y familias."),
        ],
    },
    "dansa-adults": {
        "nom": "danza para adultos",
        "nom_wa": "danza para adultos",
        "title": "clases de danza para adultos en Barcelona · escola de dansa cristina colomé",
        "desc": "clases de danza para adultos en Sant Gervasi (Barcelona): clásico, contemporáneo, jazz, hip-hop, claqué y más, de iniciación a avanzado. 1ª clase gratuita.",
        "h1": "danza para adultos",
        "intro": "nunca es tarde para empezar a bailar — ni para volver. grupos de adultos de todos los niveles, por las noches y por las mañanas, sin presión y con muy buen ambiente.",
        "per_a_qui": "tanto si no has bailado nunca como si lo dejaste hace años, tenemos un grupo para ti: por las noches (de 18.30 a 21.30) hay clásico, contemporáneo, jazz, hip-hop, claqué, español, danza oriental y heels por niveles — y por las mañanas, barre para empezar el día con energía. sin exámenes ni presión: bailar para disfrutar.",
        "beneficis": [
            ("desconectar de verdad", "una hora de danza es una hora sin móvil, sin trabajo y sin pantallas."),
            ("forma física sin gimnasio", "cardio, fuerza, flexibilidad y postura — todo bailando."),
            ("aprender siempre", "el cerebro adulto agradece retos nuevos: coreografía, música y memoria en acción."),
            ("gente como tú", "los grupos de adultos son pequeñas familias: se viene a bailar y uno se queda por la gente."),
        ],
        "disciplines": [
            ("ballet clásico", "ballet-classic", "de iniciación a avanzado — también si empiezas de cero"),
            ("contemporáneo", "dansa-contemporania", "expresión y movimiento libre, intermedio y avanzado"),
            ("jazz", "jazz", "grupos básico e intermedio, energía pura"),
            ("hip-hop", "hip-hop", "urbano para adultos avanzados"),
            ("claqué", "claque", "el ritmo en los pies, nivel intermedio"),
            ("baile español", "ball-espanyol", "tradición y carácter, nivel intermedio"),
            ("danza oriental", "dansa-oriental", "danza del vientre, nivel avanzado"),
            ("heels", "k-pop-heels", "actitud sobre tacones, nivel avanzado"),
            ("yoga, barre y zumba", "cos-benestar", "cuidarse bailando, mañanas y noches"),
            ("fit dance & femme empower", "fit-dance", "entrenar bailando, en grupo y con actitud"),
        ],
        "faqs": [
            ("tengo más de 40/50/60 años: ¿puedo empezar?",
             "¡claro que sí! en la escuela decimos que bailamos de 0 a 99. elige una disciplina de iniciación o el barre y empieza a tu ritmo."),
            ("¿qué horarios tienen las clases de adultos?",
             "la mayoría son por la noche, entre las 18.30 y las 21.30, perfectas para después del trabajo. y el barre, los lunes y miércoles a las 11 de la mañana."),
            ("¿cuánto cuestan las clases para adultos?",
             "desde 60 €/mes (1 día por semana) hasta 104 €/mes (4 días de clases de más de una hora), con opción trimestral. la primera clase de prueba es gratuita."),
        ],
    },
    # pàgines custom: cos i ld s'injecten des de genera_pagines.py
    "horaris": {
        "nom": "horarios",
        "nom_wa": "danza",
        "title": "horarios de las clases · curso 2026–27 · escola de dansa cristina colomé",
        "desc": "todos los horarios de las clases de danza del curso 2026–27 en la escuela Cristina Colomé (Sant Gervasi, Barcelona): día a día, por actividad, grupo y sala.",
        "h1": "horarios",
        "intro": "la parrilla completa del curso 2026–27, día a día: tardes para infantiles y juveniles, noches para adultos y mañanas de barre. salas H, N y C.",
        "etiqueta_capsal": "curso 2026–27 · parrilla completa",
    },
    "preus": {
        "nom": "precios",
        "nom_wa": "danza",
        "title": "precios y tarifas · curso 2026–27 · escola de dansa cristina colomé",
        "desc": "tarifas del curso 2026–27 de la escuela de danza Cristina Colomé (Barcelona): cuotas mensuales y trimestrales según días por semana, matrícula y cursos especiales. 1ª clase gratuita.",
        "h1": "precios",
        "intro": "las tarifas del curso 2026–27: paga por mes o por trimestre, con 1, 2, 3 o 4 días de clase a la semana. la primera clase de prueba es gratuita.",
        "etiqueta_capsal": "curso 2026–27 · tarifas",
    },
}
